source "https://rubygems.org"

# Fastlane and related gems
gem "fastlane", "~> 2.228"
gem "xcpretty", "~> 0.4"

# Load plugins if they exist
plugins_path = File.join(File.dirname(__FILE__), "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)